# Generated by Django 5.1.15 on 2025-12-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر سامانه'), ('support', 'پشتیبان'), ('provider', 'ارائه دهنده خدمات'), ('normal', 'کاربر عادی')], default='normal', max_length=10, verbose_name='نقش کاربر'),
        ),
    ]
